### ISSUE TITLE
Crash when try to pick a start of a range.

### ISSUE THREAD

**Issue by kannabi** [ArchitShah248/CalendarDateRangePicker#8]
I just add a widget to my layout without any custom attributes. So I open it and try to pick start of a range and got crash. There is stack trace: 
 java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.GradientDrawable
                      at com.archit.calendardaterangepicker.customviews.DateRangeMonthView.makeAsSelectedDate(DateRangeMonthView.java:359)
                      at com.archit.calendardaterangepicker.customviews.DateRangeMonthView.drawDayContainer(DateRangeMonthView.java:276)
                      at com.archit.calendardaterangepicker.customviews.DateRangeMonthView.drawCalendarForMonth(DateRangeMonthView.java:248)
                      at com.archit.calendardaterangepicker.customviews.DateRangeMonthView.access$200(DateRangeMonthView.java:32)
                      at com.archit.calendardaterangepicker.customviews.DateRangeMonthView$1.onClick(DateRangeMonthView.java:145)
                      at android.view.View.performClick(View.java:6256)
                      at android.view.View$PerformClick.run(View.java:24704)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6590)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by ArchitShah248** [comment]
Hey @kannabi : Thank you for posting this issue. Can you please provide more detail on that e.g. OS, any specific device, specific test scenario etc.. ? 

Here I am not able to reproduce.

Thanks in advance.

**Comment by kannabi** [comment]
It was Android 8.0. I just add it to the view of DialogFragment class and try to open it. So I'd got a crash.
